### ISSUE TITLE
Section for Oracles

### ISSUE THREAD

**Issue by supra-simeon** [DefiKingdoms/docs#65]
Hey, everyone 🙂. I'm not sure if this has been asked/raised before but is there a section for adding documentation about Oracles? SupraOracles has integrated DFKchain (testnet) for both [Price Feeds](https://data.supraoracles.com/networks/dfk_chain) and [VRFs](https://supraoracles.com/docs/vrf1/a-deeper-dive-into-supra-vrf). We have documentation tailored for the DFKchain testnet for both products and would love to get it included in DFK dev docs.

Price feeds data and VRF service is available on testnet only with Mainnet coming in Q1 2023. I would appreciate it if anyone could point me in the right direction. Thank you 🫶🏽

**Comment by MrZipper7** [comment]
The provided details for both have been added to the DFK Chain section of our developer documentation! See: https://devs.defikingdoms.com/dfk-chain/ecosystem-partners. Appreciate it!
